name: Ruff

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install mise
        uses: jdx/mise-action@v2
      
      - name: Setup dependencies with mise
        run: mise install
      
      - name: Run ruff linter
        run: mise run lint
      
      - name: Run ruff formatter check
        run: mise run format-check
      
      - name: Set the default branch for testing
        run: git config --global init.defaultBranch main
      
      - name: Run tests
        run: mise run test